version: "3.9"

services:
  db:
    image: postgres:16
    container_name: cadete-db
    environment:
      POSTGRES_DB: cadete
      POSTGRES_USER: cadete
      POSTGRES_PASSWORD: cadete
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: cadete-backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/cadete
      SPRING_DATASOURCE_USERNAME: cadete
      SPRING_DATASOURCE_PASSWORD: cadete
      # se quiser for√ßar:
      # SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: cadete-frontend
    depends_on:
      - backend
    ports:
      - "5173:80"   # navegador acessa :5173, Nginx responde na 80 dentro do container

volumes:
  db_data:
